Development of text spotting code
maps-as-data/MapReader pull request #536
Opened 2024-11-27 13:34 UTC by rwood-97

### Summary

This PR adds some development to the text spotting code:
- Adds dataclasses for text predictions
- Relatively minor refactoring
- Adds saving text predictions as centroid when calling `save_to_geojson`
- [x] Adding loading/saving of predictions

Fixes #504 
Fixes #498 
Addresses #533 

### Checklist before assigning a reviewer (update as needed)

- [x] Self-review code
- [x] Update changelog
- [x] Ensure submission passes current tests
- [x] Add tests
- [x] Update relevant docs

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

2024-12-12 17:30 UTC, kallewesterling requested changes
A few comments, with suggestions of a few things to change here. Nothing major - looks great otherwise!!! :)

2024-12-12 17:30 UTC, kallewesterling commented on mapreader/spot_text/runner_base.py
> +        path_save: str | pathlib.Path,
I think this one should just be called `path`? Since save is in the method name, we don't need to repeat it in the keyword arguments?

2024-12-16 08:49 UTC, rwood-97 commented on mapreader/spot_text/runner_base.py
>      def save_to_geojson(
yes this might actually be better

2024-12-19 09:46 UTC, kallewesterling approved these changes

2024-12-19 16:32 UTC, merged